export const TOPIC_ORDER = [
  // ── Fundamentals ──────────────────────────────────────────────
  'java-basics',
  'java/variables_data_types',
  'java/java_operators',

  // ── Object-Oriented Programming ───────────────────────────────
  'java/java_oop_concepts',

  // ── Core Java ─────────────────────────────────────────────────
  'java/java_collections_framework',
  'java/java_streams_api',

  // ── Advanced ──────────────────────────────────────────────────
  'multithreading',
  'java/java_21_modern_concurrency',

  // ── Java Interview Q&A ──────────────────────────────────────────
  'questions and answers/java/multithreading_30qa',
  'questions and answers/java/java8_interview_prep (2)',

  // ── DSA Interview Q&A ───────────────────────────────────────────
  'questions and answers/dsa/dsa_top50_q1_5',
  'questions and answers/dsa/dsa_top50_q6_10',
  'questions and answers/dsa/dsa_top50_q11_15',
  'questions and answers/dsa/dsa_top50_q16_20',
  'questions and answers/dsa/dsa_top50_q21_25',
  'questions and answers/dsa/dsa_top50_q26_30',

  // ── Spring Boot ───────────────────────────────────────────────
  'springboot',

  // ── Spring Boot Interview Q&A ──────────────────────────────────
  'questions and answers/spring boot/springboot_qa_p1',
  'spring-boot/spring_boot_internals',
  'spring-boot/stereotypes',
  'spring-boot/stereotype_annotations',
  'spring-boot/bean_scopes',
  'spring-boot/autowired_internals',
  'spring-boot/ambiguity_resolution',
  'spring-boot/request_lifecycle',
  'spring-boot/restcontroller',
  'spring-boot/request_mapping_annotations',
  'spring-boot/path_variable_vs_request_param',
  'spring-boot/global_error_handling',
  'spring-boot/spring_data_jpa',
  'spring-boot/jpa_lifecycle',
  'spring-boot/onetoone_mapping',
  'spring-boot/onetomany_mapping',
  'spring-boot/manytomany_mapping',
  'spring-boot/transactional_guide',
  'spring-boot/transaction_propagation',
  'spring-boot/rollback_mechanism',
  'spring-boot/spring_security',
  'spring-boot/authentication_vs_authorization',
  'spring-boot/aws_day19_sqs_sns_eventbridge',
  'spring-boot/spring_data_jpa_architecture',


  // ── AWS Cloud ─────────────────────────────────────────────────
  'aws/aws_day1_full_session',
  'aws/aws_day2_ec2',
  'aws/aws_day3_s3',
  'aws/aws_day4_vpc',
  'aws/aws_day5_iam',
  'aws/aws_day6_cli_sdk',
  'aws/aws_day7_ec2_deep',
  'aws/aws_day8_alb_asg',
  'aws/aws_day9_rds',
  'aws/aws_day10_e2e_deployment',
  'aws/aws_day11_route53_cloudfront',
  'aws/aws_day12_ecs_docker',
  'aws/aws_day13_elasticache_dynamodb',
  'aws/aws_day14_cloudwatch',
  'aws/aws_day15_cicd',

  // ── Kafka Messaging ───────────────────────────────────────────
  'kafka/kafka-basics',
  'kafka/kafka-architecture',
  'kafka/spring-kafka',
  'kafka/what_is_consumer_group',
  'kafka/what_is_kafka',
  'kafka/what_is_topic',
  'kafka/what_is_partition',
  'kafka/what_is_offset',
  'kafka/what_is_replication',
  'kafka/what_is_isr',
  'kafka/what_is_rebalancing',
  'kafka/what_is_consumer_lag',
  'kafka/what_is_log_compaction',
  'kafka/what_is_dlt',
  'kafka/what_is_idempotent_producer',
  'kafka/kafka_architecture',
  'kafka/kafka_components',
  'kafka/kafka_producer_api',
  'kafka/kafka_consumer_api',
  'kafka/kafka_streams',
  'kafka/kafka_zookeeper',
  'kafka/kafka_load_balancing',
  'kafka/leader_and_follower',
  'kafka/consumer_group',

  // ── Kafka Interview Q&A ───────────────────────────────────────
  'kafka/kafka-70-qa',
  'questions and answers/kafka/kafka_top20',
  'kafka/at_most_once_vs_at_least_once_vs_exactly_once',
  'kafka/auto_commit_vs_manual_commit',
  'kafka/kafka_vs_rabbitmq',
  'kafka/how_kafka_achieves_scalability',
  'kafka/what_happens_when_broker_crashes',
  'kafka/explain_producer_acknowledgment',
  'kafka/how_do_you_integrate_kafka_with_spring_boot',
  'kafka/describe_a_kafka_implementation_from_your_project',

  // ── Microservices ─────────────────────────────────────────────
  'microservice/service-discovery',
  'microservice/api-gateway',
  'microservice/resilience4j',
  'microservice/api_gateway',
  'microservice/async_and_eda',
  'microservice/database_per_service',
  'microservice/distributed_tracing',
  'microservice/interservice_communication',
  'microservice/rate_limiting',
  'microservice/saga_pattern',
  'microservice/service_discovery (2)',

  // ── Microservices Interview Q&A ────────────────────────────────
  'questions and answers/microservices/microservices_top10',

  // ── 60-Day Study Plan Checklists ──────────────────────────────
  'checklists/day1',
  'checklists/day2',
  'checklists/day3',
  'checklists/day4',
  'checklists/day5',
  'checklists/day6',
  'checklists/day7',
  'checklists/day8',
  'checklists/day9',
  'checklists/day10',
  'checklists/day11',
  'checklists/day12',
  'checklists/day13',
  'checklists/day14',
  'checklists/day15',
  'checklists/day16',
  'checklists/day17',
  'checklists/day18',
  'checklists/day19',
  'checklists/day20',
  'checklists/day21',
  'checklists/day22',
  'checklists/day24',
  'checklists/day29',
  'checklists/day30',
  'checklists/day31',
  'checklists/day32',
  'checklists/day33',
  'checklists/day43',
  'checklists/day44',
  'checklists/day46',
  'checklists/day47',
  'checklists/day48',
  'checklists/day49',
  'checklists/day51',
  'checklists/day52',
  'checklists/day53',
  'checklists/day55',
  'checklists/day56',
  'checklists/day57',
  'checklists/day58',
  'checklists/day59',
  'checklists/day60',

  // ── Key Topics: System Design & Architecture ──────────────────
  'key-topics/acid_properties_masterclass',
  'key-topics/api_gateway_masterclass',
  'key-topics/api_rate_limiting_masterclass',
  'key-topics/client_server_model_architecture',
  'key-topics/enterprise_load_balancer_flow',
  'key-topics/enterprise_service_discovery_reel',
  'key-topics/fintech_resilience_masterclass',
  'key-topics/fintech_saga_pattern_masterclass',
  'key-topics/microservice_communication_masterclass',
  'key-topics/saga_pattern_flow',
  'key-topics/spring_cloud_gateway_flow',
  'key-topics/system_design_sandbox',

  // ── Key Topics: Java Memory & Concurrency Reels ──────────────
  'key-topics/concurrenthashmap_internals_reel',
  'key-topics/functional_interfaces_reel',
  'key-topics/hashmap_internal_flow_reel',
  'key-topics/java_8_aurora_reel',
  'key-topics/java_core_concepts_reel',
  'key-topics/java_memory_internals_reel',
  'key-topics/java_string_internals_reel',
  'key-topics/jvm_architecture_deep_dive',
  'key-topics/spring_bean_lifecycle_reel',

  // ── Key Topics: Design Patterns & Web Masterclasses ──────────
  'key-topics/enterprise_rest_masterclass',
  'key-topics/factory_patterns_masterclass',
  'key-topics/java_exceptions_masterclass',
  'key-topics/jwt_stateless_auth_flow',
  'key-topics/singleton_pattern_masterclass',
  'key-topics/spring_boot_3_tier_architecture',
  'key-topics/spring_boot_actuator_claude_theme',
  'key-topics/spring_boot_configuration_reel',
  'key-topics/spring_boot_request_flow',
  'key-topics/spring_boot_routing_engine',
  'key-topics/spring_mvc_routing_engine_reel',

  // ── Complete Request Flow ─────────────────────────────────────
  'flow-explainer/01_browser',
  'flow-explainer/02_dns',
  'flow-explainer/03_networking',
  'flow-explainer/04_http_https',
  'flow-explainer/05_firewall',
  'flow-explainer/06_cdn',
  'flow-explainer/07_load_balancer',
  'flow-explainer/08_api_gateway',
  'flow-explainer/09_reverse_proxy',
  'flow-explainer/10_spring_boot_flow',
  'flow-explainer/11_redis_caching',
  'flow-explainer/12_database',
  'flow-explainer/13_database_pooling',
  'flow-explainer/14_message_queue_kafka',
  'flow-explainer/15_async_workers',
  'flow-explainer/16_third_party_apis',
  'flow-explainer/17_service_discovery',
  'flow-explainer/18_distributed_tracing',
  'flow-explainer/19_docker_kubernetes',
  'flow-explainer/20_complete_flow',
];